
server:
  port: 8081

spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     username: iotlog
     password: iotlog123
     url: jdbc:mysql://134.175.180.227:3306/iotlog?useUnicode=true&characterEncoding=utf-8
     type: com.zaxxer.hikari.HikariDataSource
     hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1 from dual

  #mvc:
   # static-path-pattern: /static/**
  logging:
    level:
      root: info


    
